version: "3.5"

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./api-gateway/
    ports:
      - "3030:3030"
    volumes:
      - ./api-gateway:/usr/app
    networks:
      - challenge
    command: "yarn start"

  products:
    container_name: products
    restart: always
    build: ./products-api/
    ports:
      - "3034:3034"
    env_file: ./products-api/.env
    volumes:
      - ./products-api:/usr/app
    networks:
      - challenge
    command: "yarn start"

  users:
    container_name: users
    build: ./users-api/
    restart: always
    ports:
      - "3032:3032"
    env_file: ./users-api/.env
    volumes:
      - ./users-api:/usr/app
    networks:
      - challenge
    command: "yarn start"

networks:
  challenge:
    name: challenge
    driver: bridge

  # product-db:
  #   container_name: product-pg
  #   image: postgres
  #   env_file: .env
  #   networks:
  #     - fullstack-challenge

  # user-db:
  #   container_name: user-pg
  #   image: postgres
  #   env_file: .env
  #   networks:
  #     - fullstack-challenge
